core/urls.py
from django.urls import path
from .views import (index, contact_view, dashboard_view, profile_settings_view, 
                    profile_view, plan_detail_view, send_payment_review, 
                    plans_view,deposit_view,send_deposit_review,transaction_view,deposits_view,search_view,withdraw_view,withdrawal_view)

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('home/', index, name='index'),
    path('contact', contact_view, name='contact'),
    path('app/dashboard',dashboard_view, name='dashboard'),
    path('app/dashboard/',dashboard_view, name='dashboard'),
    path('app/deposit',deposit_view, name='deposit'),
    path('app/deposit/payment/',send_deposit_review, name='payment'),
    path('app/deposit/payment',send_deposit_review, name='payment'),
    path('app/profile-settings', profile_settings_view, name='profile-settings'),
    path('app/profile', profile_view, name='profile'),
    path('app/plan/<pid>/', plan_detail_view, name='plan-detail'),
    path('app/plans', plans_view, name='plans'),
    path('app/transactions', transaction_view, name='transactions'),
    path('app/deposits', deposits_view, name='deposits'),
    path('app/withdraw', withdraw_view, name="withdraw"),
    path('app/withdrawals', withdrawal_view, name="withdrawals"),
    path("send-payment-review/<pid>/", send_payment_review, name="send-payment-review"),
    path('search/', search_view, name='search'),

]

metafinance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.views.static import serve
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include('core.urls')),
    path("", include('userauths.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.custom_error_page'
handler500 = 'core.views.custom_error_page1'

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('user/sign-up/', views.register_view, name= "sign-up"),
    path('user/sign-in/', views.login_view, name="sign-in"),
    path('logout', views.logout_view, name="logout"),
    path('lockscreen', views.lock_screen_view, name='lockscreen'),
]

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from userauths.models import User
from django.utils.html import mark_safe

from datetime import timedelta


# Create your models here.
STATUS_CHOICE = (
    ("not processed", "Not Processed"),
    ("processing", "Processing"),
    ("paid", "Paid"),
)
STATUS = (
    ("daily", "daily"),
    ("weekly", "weekly"),
    ("monthly", "monthly"),
    ("hourly", "hourly"),
)
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)
class Plan(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="plan", alphabet="abcdefgh12345") #product uuid field
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default="Plan")
    description = models.TextField(null=True, blank=True)
    initial = models.CharField(max_length=7, default="BTC")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    least_amount = models.IntegerField(default="100")
    max_amount = models.IntegerField(default="100")
    interval = models.CharField(choices=STATUS, max_length=16, default="daily")
    invested_amount = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    percentage_return = models.DecimalField(max_digits=1000, decimal_places=2, default="1.99")
    featured = models.BooleanField(default=False)
    payment_status = models.CharField(choices=STATUS_CHOICE, max_length=16, default="in_review")
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)
    class Meta:
        verbose_name_plural = "Plans"

    def __str__(self):
        return self.title
    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    def get_profit(self):
        value = ((self.percentage_return)/100)*self.invested_amount
        profit = self.invested_amount + value
        return profit

class UserComplaints(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    question = models.CharField(max_length=50)
    question_details = models.TextField(null=True, blank=True)
    class Meta:
        verbose_name_plural = "User Complaints"
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from core.models import UserComplaints


PROBLEMS = (
    ("Account", "Account"),
    ("Registering/Authorizing", "Registering/Authorizing"),
    ("Using Website", "Using Website"),
    ("Troubleshooting", "Troubleshooting"),
    ("Other", "Other"),
)



class ContactForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Name","class": "sppb-form-control","id":"sppb-form-builder-field-1"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Your Account Email", "class": "sppb-form-control","id":"sppb-form-builder-field-2"}))
    question = forms.ChoiceField(choices=PROBLEMS, widget=forms.Select(attrs={"placeholder": "This question is about..", "class": "sppb-form-control","id":"sppb-form-builder-field-0"}))
    question_details = forms.CharField(widget=forms.Textarea(attrs={"placeholder": 'I have a problem with...','class': 'sppb-form-control',"id":"sppb-form-builder-field-3"}))
    
    class Meta:
        model = UserComplaints
        fields = ['name','email','question','question_details']

core/views.py
from django.shortcuts import render,redirect
import django
from django.contrib import messages
from .models import Plan, UserComplaints
from core.forms import ContactForm
from userauths.forms import TransactionForm, WithdrawForm
from userauths.models import Transaction, Deposit, Withdraw
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import REDIRECT_FIELD_NAME


def login_required(
    function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url='userauths:sign-in'
):
    """
    Decorator for views that checks that the user is logged in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name,
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


def custom_error_page(request,exception):
    return render(request, 'errors/custom_error.html')
def custom_error_page1(request):
    return render(request, 'errors/500.html')
def index(request):
    plans = Plan.objects.all()
    context = {
        "plan": plans,
        'user': request.user,
    }
    return render(request, "core/index.html",context)



def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Thanks, message sent succesfully")
            return redirect('core:index')
    else:
        form = ContactForm()

    return render(request, 'core/contact.html', {'form': form})


@login_required
def dashboard_view(request):
    plans = Plan.objects.all()
    
    context = {
        "plans": plans
    }
    
    return render(request, "core/dashboard-crypto.html", context)


@login_required
def profile_view(request):
    return render(request, "core/pages-profile.html")

@login_required
def withdrawal_view(request):
    user_withdrawals = Withdraw.objects.filter(user=request.user).order_by('-timestamp')
    context = {'user_withdrawals': user_withdrawals}
    return render(request, "core/withdrawals.html", context)
@login_required
def profile_settings_view(request):

    return render(request, "core/pages-profile-settings.html")


@login_required
def plans_view(request):
    plans = Plan.objects.all()
    context = {
        "plan": plans
    }
    return render(request, "core/product-list.html", context)

@login_required
def plan_detail_view(request, pid):
    form = TransactionForm()
    product = Plan.objects.get(pid=pid)
    products = Plan.objects.filter().exclude(pid=pid)
    p_image = product.product_image()
    
    context = {
        "form": form,
        "p": product,
        "p_image": p_image,
        "products": products,
        
    }
    
    return render(request, "core/product-detail.html", context)

@login_required
def deposit_view(request):
    return render(request, "core/deposit.html")

@login_required
def send_deposit_review(request):
    user = request.user
    review = Deposit.objects.create(
        user = user,
        amount = request.POST['deposit'],
        currency = request.POST['options'],
        wallet_address = request.POST['address'],
    )
    return render(request, "core/wallet-details.html")

@login_required
def send_payment_review(request, pid):
    user = request.user
    plan = Plan.objects.get(pid=pid)
    least_amount = plan.least_amount
    max_amount = plan.max_amount
    amount = Decimal(request.POST['amount'])
    if float(request.POST['amount']) <= user.total_deposit:
        user.total_deposit -= amount
        user.save()
        user.total_invested += amount
        user.save()


        review = Transaction.objects.create(
            user = user,
            title = plan.title,
            interval = plan.interval,
            percentage_return = plan.percentage_return,
            amount = request.POST['amount'],
            least_amount = least_amount,
            max_amount = max_amount,
        )
    else:
        messages.warning(request,"Insufficient Balance, Please Deposit or Choose A Plan")
        return redirect('core:deposit')
    date = review.timestamp
    tid = review.transaction_id
    context = {
        "amount":amount,
        "plan":plan,
        "date": date,
        "tid": tid,
    }

    return render(request,"core/success.html", context)

@login_required
def transaction_view(request):

    user_transactions = Transaction.objects.filter(user=request.user).order_by('-timestamp')
    context = {'user_transactions': user_transactions}
    return render(request, "core/transactions.html", context)


@login_required
def deposits_view(request):

    user_deposits = Deposit.objects.filter(user=request.user).order_by('-timestamp')
    context = {'user_deposits': user_deposits}
    return render(request, "core/deposits.html", context)

@login_required
def withdraw_view(request):
    user = request.user
    if request.method == 'POST':
        if float(request.POST['amount']) <= user.total_balance:
            form = WithdrawForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,"Withdrawal placement pending")
                return redirect('core:dashboard')
            else:
                messages.warning(request,"Invalid Address")
                return redirect('core:withdraw')
        else:
            messages.warning(request,"Insufficient Balance")
            return redirect('core:withdraw')
    else:
        form = WithdrawForm()
    return render(request,"core/withdraw.html",{'form':form})

@login_required
def search_view(request):
    query = request.GET.get("search")

    plans = Plan.objects.filter(title__icontains=query).order_by("-date")
    transactions = Transaction.objects.filter(title__icontains=query).order_by("-timestamp")
    context={
        "plans": plans,
        "query": query,
        "transactions": transactions,
    }
    return render(request, "core/search.html", context)

templates/core/product-list.html
{% extends "partials/appbase.html" %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- removeNotificationModal -->
<div id="removeNotificationModal" class="modal fade zoomIn" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                    id="NotificationModalbtn-close"></button>
            </div>
            <div class="modal-body">
                <div class="mt-2 text-center">
                    <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop"
                        colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>
                    <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                        <h4>Are you sure ?</h4>
                        <p class="text-muted mx-4 mb-0">Are you sure you want to remove this Notification ?</p>
                    </div>
                </div>
                <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
                    <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn w-sm btn-danger" id="delete-notification">Yes, Delete It!</button>
                </div>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- removeNotificationModal -->
<div id="logoutNotificationModal" class="modal fade zoomIn" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                    id="NotificationModalbtn-close"></button>
            </div>
            <div class="modal-body">
                <div class="mt-2 text-center">
                    <lord-icon src="https://cdn.lordicon.com/wtnrotmp.json" trigger="loop"
                        colors="primary:#f7b84b,secondary:#de000b" style="width:100px;height:100px"></lord-icon>
                    </lord-icon>
                    <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                        <h4>Are you sure ?</h4>
                        <p class="text-muted mx-4 mb-0">Are you sure you want to Logout ?</p>
                    </div>
                </div>
                <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
                    <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Close</button>
                    <a type="button" href="{% url "userauths:logout"%}" class="btn w-sm btn-danger"
                        id="delete-notification">Yes, Logout!</a>
                </div>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- ========== App Menu ========== -->
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
        <!-- Dark Logo-->
        <a href="index.html" class="logo logo-dark">
            <span class="logo-sm">
                <img src="{% static 'asset/images/logo-sm.png' %}" alt="" height="22">
            </span>
            <span class="logo-lg">
                <img src="{% static 'asset/images/logo-dark.png' %}" alt="" height="17">
            </span>
        </a>
        <!-- Light Logo-->
        <a href="/" class="logo logo-light">
            <span class="logo-sm">
                <img src="{% static 'asset/images/logo-sm.png' %}" alt="" height="22">
            </span>
            <span class="logo-lg">
                <img src="{% static 'asset/images/site_icon.svg' %}" alt="" height="18">
            </span>
        </a>
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover"
            id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">

            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">

                <li class="nav-item">
                    <a href="{% url "core:profile" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-account-circle-line"></i>
                        <span data-key="t-pages">Profile</span>
                    </a>
                  
                </li>
                
                <li class="nav-item">
                    <a href="{% url "core:deposit" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-bank-fill"></i>
                        <span data-key="t-pages">Deposit</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:withdraw" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-arrow-left-down-line"></i>
                        <span data-key="t-pages">Withdraw</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:deposits" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-exchange-fill"></i>
                        <span data-key="t-pages">Deposits</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:withdrawals" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-money-dollar-circle-line"></i>
                        <span data-key="t-pages">Withdrawals</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:plans" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-line-chart-fill"></i>
                        <span data-key="t-pages">Investment Plans</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:transactions" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-history-fill"></i>
                        <span data-key="t-pages">Transaction History</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:profile" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-settings-3-fill"></i>
                        <span data-key="t-pages">Settings</span>
                    </a>
                  
                </li>
                <li class="nav-item">
                    <a href="{% url "core:profile-settings" %}" class="nav-link menu-link"  aria-controls="sidebarPages" >
                        <i class="ri-user-fill"></i>
                        <span data-key="t-pages">Personal Details</span>
                    </a>
                  
                </li>

                <li class="nav-item">
                    <a href="{% url "userauths:lockscreen"%}" class="nav-link menu-link" aria-controls="sidebarPages" >
                        <i class="ri-lock-fill"></i>
                        <span data-key="t-pages">Lock Screen</span>
                    </a>

                </li>

                <a class="nav-link menu-link" href="#" onclick="history.back()" aria-controls="sidebarPages">
                    <i class="las la-arrow-left"></i> <span data-key="t-pages">Back</span>
                </a>
                
               

            </ul>
        </div>
        <!-- Sidebar -->
    </div>


    <div class="sidebar-background"></div>
</div>
<!-- Left Sidebar End -->
<!-- Vertical Overlay-->
<div class="vertical-overlay"></div>

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0">Plans</h4>

                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="/">Bittradexchange</a></li>
                                        <li class="breadcrumb-item active">Plans</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <div class="row">
                        {% for p in plan %}
                        <div class="col-xxl-3 col-lg-6">
                            <div class="card pricing-box">
                                <div class="card-body bg-light m-2 p-4">
                                    <div class="d-flex align-items-center mb-3">
                                        <div class="flex-grow-1">
                                            <h5 class="mb-0 fw-semibold">{{p.title}}</h5>
                                        </div>
                                        <div class="ms-auto">
                                            <h3 class="annual mb-0" style="font-size: 16px;"> ${{p.least_amount|intcomma}} - ${{p.max_amount|intcomma}} <small class="fs-13 text-muted">/{{p.interval|capfirst}}</small></h3>
                                        </div>
                                    </div>

                                    <p class="text-muted">{{p.description}}.</p>
                                    <ul class="list-unstyled vstack gap-3">
                                        <li>
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 text-success me-1">
                                                    <i class="ri-checkbox-circle-fill fs-15 align-middle"></i>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <b>Initial:</b> {{p.initial}}
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 text-success me-1">
                                                    <i class="ri-checkbox-circle-fill fs-15 align-middle"></i>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <b>Plan Id:</b> {{p.pid}}
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 text-success me-1">
                                                    <i class="ri-checkbox-circle-fill fs-15 align-middle"></i>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <b>Percentage Return:</b> {{p.percentage_return}}%
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 text-success me-1">
                                                    <i class="ri-checkbox-circle-fill fs-15 align-middle"></i>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <b>Interval:</b> {{p.interval|capfirst}}
                                                </div>
                                            </div>
                                        </li>

                                    </ul>
                                    <div class="mt-3 pt-2">
                                        <a href="{% url "core:plan-detail" p.pid %}" class="btn btn-info w-100">Invest In Plan</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                        <!--end col-->


                        <!--end col-->
                    </div>
                    <!--end row-->


                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

    {% endblock content %}