core/urls.py
from django.urls import path
from .views import (index, contact_view, dashboard_view, profile_settings_view, 
                    profile_view, plan_detail_view, send_payment_review, 
                    plans_view,deposit_view,send_deposit_review,transaction_view,deposits_view,search_view,withdraw_view,withdrawal_view)

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('home/', index, name='index'),
    path('contact', contact_view, name='contact'),
    path('app/dashboard',dashboard_view, name='dashboard'),
    path('app/dashboard/',dashboard_view, name='dashboard'),
    path('app/deposit',deposit_view, name='deposit'),
    path('app/deposit/payment/',send_deposit_review, name='payment'),
    path('app/deposit/payment',send_deposit_review, name='payment'),
    path('app/profile-settings', profile_settings_view, name='profile-settings'),
    path('app/profile', profile_view, name='profile'),
    path('app/plan/<pid>/', plan_detail_view, name='plan-detail'),
    path('app/plans', plans_view, name='plans'),
    path('app/transactions', transaction_view, name='transactions'),
    path('app/deposits', deposits_view, name='deposits'),
    path('app/withdraw', withdraw_view, name="withdraw"),
    path('app/withdrawals', withdrawal_view, name="withdrawals"),
    path("send-payment-review/<pid>/", send_payment_review, name="send-payment-review"),
    path('search/', search_view, name='search'),

]

metafinance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.views.static import serve
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", include('core.urls')),
    path("", include('userauths.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.custom_error_page'
handler500 = 'core.views.custom_error_page1'

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('user/sign-up/', views.register_view, name= "sign-up"),
    path('user/sign-in/', views.login_view, name="sign-in"),
    path('logout', views.logout_view, name="logout"),
    path('lockscreen', views.lock_screen_view, name='lockscreen'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from shortuuid.django_fields import ShortUUIDField
from decimal import Decimal
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
from django.utils import timezone
# Create your models here.
STATUS = (
    ("daily", "daily"),
    ("weekly", "weekly"),
    ("monthly", "monthly"),
    ("hourly", "hourly"),
)
class User(AbstractUser):
    is_email_verified = models.BooleanField(default=False)
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)
    total_balance = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    total_invested = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    total_deposit = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    referral_code = ShortUUIDField(unique=True, length=10, max_length=20, prefix="meta", alphabet="abcdefgh12345")
    referred = models.CharField(max_length=20, blank=True)
    contact = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    def save(self, *args, **kwargs):
        self.total_balance = Decimal(self.total_deposit) + Decimal(self.total_invested)
        super().save(*args, **kwargs)
    def __str__(self):
        return self.username

        



class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=100, decimal_places=2, default="0.00")
    title = models.CharField(max_length=50, blank=True)
    interval = models.CharField(choices=STATUS, max_length=16, default="daily")
    percentage_return = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    least_amount = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    max_amount = models.DecimalField(max_digits=1000, decimal_places=2, default="0.00")
    transaction_id = ShortUUIDField(unique=True, length=10, max_length=20, prefix="TRX", alphabet="abcdefgh12345")
    timestamp = models.DateTimeField(auto_now_add=True)

class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    currency = models.CharField(max_length=25, blank=True)
    wallet_address = models.CharField(max_length=100, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    confirmed = models.BooleanField(default=False)

    def confirm_deposit(self):
        if not self.confirmed:
            self.confirmed = True
            self.save()

            # Update user's balance
            self.user.total_deposit += self.amount
            self.user.save()

class Withdraw(models.Model):
    user = models.CharField(max_length=100)
    email = models.EmailField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=25, blank=True)
    wallet_address = models.CharField(max_length=100, blank=True)
    transaction_id = ShortUUIDField(unique=True, length=10, max_length=20, prefix="WDR", alphabet="ijklmno12345")
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Withdrawal Requests"

userauths/forms.py
import re
import hashlib
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User,Transaction, Deposit,Withdraw
from .countries import sorted_countries
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from decimal import Decimal
CURRENCY = (
    ("Bitcoin (BTC)", "Bitcoin (BTC)"),
    ("Ethereum (ETH)", "Ethereum (ETH)"),
    ("Tether (USDT)", "Tether (USDT)"),
    ("Binance Coin (BNB)", "Binance Coin (BNB)"),
)


def validate_referral_code(value):
    """
    Custom validator to check if the referral code exists in the User model.
    If it exists, create the account and add $10 to total_balance.
    If it doesn't exist, raise a ValidationError.
    """
    try:
        user = User.objects.get(referral_code=value)
        user.save()
        # Referral code exists, create account and add $10 to total_balance
        user.total_deposit += Decimal('10.00')
        user.save()
    except User.DoesNotExist:
        raise ValidationError('This referral code does not exist.')

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username","class": "form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email", "class": "form-control"}))
    address = forms.ChoiceField(choices=sorted_countries, widget=forms.Select(attrs={"placeholder": "Country", "class": "form-control"}))
    referred = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "*Optional","class": "form-control"}),validators=[validate_referral_code], required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "class": "form-control","id":"password-field"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password", "class": "form-control","id":"password-field"}))
    
    class Meta:
        model = User
        fields = ['username','email','address','referred']

class TransactionForm(forms.ModelForm):
    user = forms.EmailField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    amount = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control"}))
    least_amount = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    max_amount = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    transaction_id= forms.CharField(initial='Default Value', widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    
    class Meta:
        model = Transaction
        fields = ['user','amount','least_amount','max_amount','transaction_id']


class DepositForm(forms.ModelForm):
    user = forms.EmailField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    currency = forms.ChoiceField(choices=CURRENCY, widget=forms.Select(attrs={"placeholder": "This question is about..", "class": "form-control","id":"card-holder-input"}))
    wallet_address = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Wallet Address", "class": "form-control","id":"card-holder-input","required":True}))
    amount = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control"}))
    
    class Meta:
        model = Deposit
        fields = ['user','amount','wallet_address','currency']

class WithdrawForm(forms.ModelForm):
    user = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "Username","class": "form-control"}))
    email = forms.EmailField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control",'readonly': 'readonly'}))
    amount = forms.CharField(initial='Default Value',widget=forms.TextInput(attrs={"placeholder": "", "class": "form-control"}))
    currency = forms.ChoiceField(choices=CURRENCY, widget=forms.Select(attrs={"placeholder": "This question is about..", "class": "form-control","id":"card-holder-input"}))
    wallet_address = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Wallet Address", "class": "form-control","id":"card-holder-input","required":True}))
    
    class Meta:
        model = Withdraw
        fields = ['user','email','amount','currency','wallet_address']

userauths/views.py
from django.shortcuts import render,redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout
from userauths.models import User
from django.conf import settings





def register_view(request):

    form = UserRegisterForm()
    if request.method == "POST":
        address = request.POST['address']
        username = request.POST['username']
        form = UserRegisterForm(request.POST or None)
        
        if form.is_valid():
            
            new_user = form.save()
            
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, account created successfully")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            # send_activation_email(new_user,request)
            login(request, new_user)
            return redirect("core:dashboard")
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)

def login_view(request):
    if request.user.is_authenticated:
        return redirect("core:index")
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Successfully logged in.")
                return redirect("core:dashboard")
            else:
                messages.warning(request, "Invalid credentials, create an account.")
        except:
            messages.warning(request, f"User does not exist")


    return render(request, 'userauths/sign-in.html' )


def logout_view(request):
    logout(request)
    # messages.success(request, "User successfully logged out.")
    return redirect("core:index")

def lock_screen_view(request):
    logout(request)
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% extends "partials/auth.html" %}
{% load static %}
{% block authTitle %}Bittradexchange - Sign In{% endblock authTitle %}
{% block content %}

            <!-- Login Form
		  ========================= -->
            <div class="col-md-6 d-flex align-items-center py-5 " >
              <div class="container my-auto py-4 shadow-lg bg-white">
                <div class="row">
                  <div class="col-11 col-lg-10 mx-auto">
                    <h3 class="text-9 fw-600 text-center my-3">Sign In</h3>
                    <p class="text-center mb-4">New to Bittradexchange? <a
                        style="color: #7b5dd6; text-decoration: none; font-weight: 500;" href="{% url "userauths:sign-up" %}">Create an Account</a></p>
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}">
                                <strong>{{ message }}</strong>
                            </div>

                        {% endfor %}
                    {% endif %}
                    <script>
                        setTimeout (() => {
                            $(".alert").alert("close");
                        }, 4000)
                    </script>   
                    <form id="loginForm" method="POST">
                      {% csrf_token %}
                      <div class="mb-3">
                        <label class="form-label text-dark fw-600" for="emailAddress">Email Address</label>
                        <input type="email" name="email" class="form-control rounded-2" id="emailAddress" required=""
                          placeholder="Enter Your Email">
                      </div>
                      <div class="mb-3">
                        <label class="form-label text-dark fw-600" for="loginPassword">Password</label>
                        <input type="password"  name="password" class="form-control rounded-2" id="loginPassword"
                          required="" placeholder="Enter Password">
                      </div>
                      <div class="row mt-4">
                        <div class="col">
                          <div class="form-check">
                            <input id="remember-me" name="remember" class="form-check-input rounded-0" type="checkbox">
                            <label class="form-check-label" for="remember-me">Remember Me</label>
                          </div>
                        </div>
                      </div>
                      <div class="d-grid my-4">
                        <button style="background: #7b5dd6; color: #fff;" class="btn rounded-2" type="submit">Sign In</button>
                      </div>
                    </form>

                  </div>
                </div>
              </div>
            </div>
            <!-- Login Form End -->
{% endblock content %}

templates/userauths/sign-up.html
{% extends "partials/auth.html" %}
{% load static %}
{% block authTitle %}Bittradexchange - Create account{% endblock authTitle %}
{% block content %}
          <!-- Register Form
		  ========================= -->
          <div class="col-md-6 d-flex align-items-center py-5">
            <div class="container my-auto py-4 shadow-lg bg-white">
              <div class="row">
                <div class="col-11 col-lg-10 mx-auto">
                  <h3 class="text-9 fw-600 text-center my-3">Create an Account</h3>
                  <p class="text-center mb-4">Don't have an account? <a style="color: #7b5dd6; text-decoration: none; font-weight: 500;" href="{% url "userauths:sign-in" %}">Sign In</a></p>
                  <div class="padding_eight_all bg-white">
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong style="font-size: 13px;">{{form.errors}}</strong>
                    </div>
                    {% endif %}
                </div>
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
              </script>
                  <form id="registerForm" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Email Address</label>
                      {{form.email}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Username</label>
                      {{form.username}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="emailAddress">Country</label>
                      {{form.address}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="loginPassword">Password</label>
                      {{form.password1}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="loginPassword">Confirm Password</label>
                      {{form.password2}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label text-dark fw-600" for="loginPassword">Referral Code</label>
                      {{form.referred}}
                    </div>
                    <div class="d-grid my-4">
						<button class="btn rounded-2" style="background: #7b5dd6; color: #fff;" type="submit">Create Account</button>
					</div>
                    <p class="text-center text-muted text-2 mb-0">By creating an account, you agree to <span class="fw-bold fs-15">Bittradexchange</span> Terms and Privacy</p>
                  </form>

                </div>
              </div>
            </div>
          </div>

{% endblock content %}